

ex4:
	nvc++ -mp=gpu warmUpDevice.cpp -o warmUpDevice
	./warmUpDevice

ex5:
	nvc++ -cuda -I /appl/nvhpc/2022_2211/Linux_x86_64/22.11/examples/OpenMP/SDK/include cudaDeviceQuery.cpp -o cudaDeviceQuery
	./cudaDeviceQuery